app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    /**
    Route::get('/contact', function() {
        return 'page contact';
    });

    Route::get('/articles', function(){
        return 'Mes articles:';
    });

    Route::get('/articles/create', function() {
        return view('articles.create');
    });

    Route::delete('/articles/{id}', function($id){
       //Code pour supprimer un article
    });

    Route::post('/articles', function(Request $request) {
        dd($request->all());
    });

    Route::get('/articles/{id}', function($id){
        return 'Article n°'.$id;
    });
     */


    Route::resource('/bap', 'BapController');

    Route::resource('/resetpassword', 'PasswordController');

    Route::group(['prefix' => 'admin'], function () {
        Route::resource('/', 'AdminController');
        Route::resource('/articles', 'AdminArticleController');
        Route::resource('/bap', 'BapAdminController');
        Route::resource('/contact', 'ContactAdminController');

    });


    Route::resource('/profile', 'ProfilController');
    Route::resource('/articles', 'PostController');
    Route::resource('/comment', 'CommentController');
    Route::resource('/setadmin', 'Auth\AuthController');

    Route::resource('/contact', 'AboutController');


    Route::auth();



    Route::get('/', 'HomeController@index');






});

resources/views/home.blade.php
@extends('layouts.app', ['pageTitle' => 'Dashboard'])

@section('content')

    @if(isset($message))
        <h2>{{$message}}</h2>
    @endif

    <div class="row text-center">
        <h3 class="text-center">Bienvenue @if(Auth::check()) <strong>{{Auth::user()->name}}</strong>@endif

        </h3>

        <div class="col-md-12 text-center" style="margin-bottom: 50px;">Tu pourras naviguer sur la plupart de nos
            créations via cette page.
        </div>

        <div class="col-md-4">Pour nous envoyer un message, clique <strong><a href="{{route('contact.index')}}">ici</a></strong>
            (Section Contact)
        </div>
        <div class="col-md-4">Pour voir les articles, clique <strong><a
                        href="{{route('articles.index')}}">ici</a></strong> (Blog)
        </div>
        <div class="col-md-4">Pour accéder aux projets BAP, clique <strong><a
                        href="{{route('bap.index')}}">ici</a></strong>
            (Formulaire pour soumettre un projet)
        </div>

        <div class="col-md-4" style="margin-top: 25px;">Pour aller sur votre page profil clique en haut à droite ou
            clique <strong><a href="{{route('profile.index')}}">ici</a></strong>
            (Profile)
        </div>

        <div class="col-md-4" style="margin-top: 25px;">Pour Créer un article, clique <strong><a
                        href="{{route('articles.create')}}">ici</a></strong>
            (Créer un article)
        </div>

        <div class="col-md-4" style="margin-top: 25px;">Dashboard Administrateur, clique <strong><a
                        href="{{url('/admin')}}">ici</a></strong>
            (Pour être admin, aller dans profil, puis modifier profil)
        </div>


    </div>

@endsection