app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    /**
    Route::get('/contact', function() {
        return 'page contact';
    });

    Route::get('/articles', function(){
        return 'Mes articles:';
    });

    Route::get('/articles/create', function() {
        return view('articles.create');
    });

    Route::delete('/articles/{id}', function($id){
       //Code pour supprimer un article
    });

    Route::post('/articles', function(Request $request) {
        dd($request->all());
    });

    Route::get('/articles/{id}', function($id){
        return 'Article n°'.$id;
    });
     */


    Route::resource('/bap', 'BapController');

    Route::resource('/resetpassword', 'PasswordController');

    Route::group(['prefix' => 'admin'], function () {
        Route::resource('/', 'AdminController');
        Route::resource('/articles', 'AdminArticleController');
        Route::resource('/bap', 'BapAdminController');
        Route::resource('/contact', 'ContactAdminController');

    });


    Route::resource('/profile', 'ProfilController');
    Route::resource('/articles', 'PostController');
    Route::resource('/comment', 'CommentController');
    Route::resource('/setadmin', 'Auth\AuthController');

    Route::resource('/contact', 'AboutController');


    Route::auth();



    Route::get('/', 'HomeController@index');






});

resources/views/admin/index.blade.php
@extends('layouts.app', ['pageTitle' => 'Admin panel'])

@section('content')
    <h2>Admin Panel!</h2>

    <p>Pour accéder aux projets et les valider, cliquez <strong><a href="{{route('admin.bap.index')}}">ici</a></strong></p>
    <p>Pour accéder aux articles, au commentaires et les gérés, cliquez <strong><a href="{{route('admin.articles.index')}}">ici</a></strong></p>
    <p>Pour voire les messages que vous ont laissé vos utilisateurs, cliquez <strong><a href="{{route('admin.contact.index')}}">ici</a></strong></p>
@endsection