app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    /**
    Route::get('/contact', function() {
        return 'page contact';
    });

    Route::get('/articles', function(){
        return 'Mes articles:';
    });

    Route::get('/articles/create', function() {
        return view('articles.create');
    });

    Route::delete('/articles/{id}', function($id){
       //Code pour supprimer un article
    });

    Route::post('/articles', function(Request $request) {
        dd($request->all());
    });

    Route::get('/articles/{id}', function($id){
        return 'Article n°'.$id;
    });
     */


    Route::resource('/bap', 'BapController');

    Route::resource('/resetpassword', 'PasswordController');

    Route::group(['prefix' => 'admin'], function () {
        Route::resource('/', 'AdminController');
        Route::resource('/articles', 'AdminArticleController');
        Route::resource('/bap', 'BapAdminController');
        Route::resource('/contact', 'ContactAdminController');

    });


    Route::resource('/profile', 'ProfilController');
    Route::resource('/articles', 'PostController');
    Route::resource('/comment', 'CommentController');
    Route::resource('/setadmin', 'Auth\AuthController');

    Route::resource('/contact', 'AboutController');


    Route::auth();



    Route::get('/', 'HomeController@index');






});

resources/views/admin/articles/create.blade.php
@extends('layouts.app', ['pageTitle' => 'Ajouter un article'])

@section('content')
    @include('partials.articles.form', ['action' => 'create'])
    @include('partials.articles.errors')
@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.app', ['pageTitle' => 'Edition de l\'article n°'.$post->id])

@section('content')
    @include('partials.articles.form', ['action' => 'edit'])
    @include('partials.articles.errors')
@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.app', ['pageTitle' => 'Liste des articles'])

@section('content')




    @if(Session::has('erreur'))
        <h1>{{Session::get('erreur')}}</h1>
    @endif



    @foreach($posts as $post)
        <h3>{{$post->title}}</h3>
        <p>{{$post->content}}</p>
        <a href="{{route('admin.articles.show', $post->id)}}">
            <button>Voir l'article</button>
        </a>


            <a href="{{route('admin.articles.edit', $post->id)}}">
                <button>Editer l'article</button>
            </a>
            <form action="{{route('admin.articles.destroy', $post->id)}}" method="POST">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="DELETE">
                <button>Supprimer l'article</button>
            </form>

    @endforeach




@endsection

resources/views/admin/articles/show.blade.php
@extends('layouts.app', ['pageTitle' => 'Article n°'.$post->id])

@section('content')
    <h2>{{$post->title}}<br> Auteur: {{ $post->user->name }} </h2>
    <p>{{$post->content}}</p>

    <hr>
    @if(Auth::check())

    <h2>Publier un commentaire</h2>
    {!! Form::open(array(
    'action' => 'CommentController@store',
    'method' => 'POST'))
    !!}

    <div class="form-group">
        {!! Form::hidden('post_id', $post->id, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group">
        {!! Form::textarea('content', null, ['class' => 'form-control']) !!}
    </div>

    {!! Form::submit('Envoyer', ['class' => 'btn btn-block']) !!}
    {!! Form::close() !!}

    @include('partials.articles.errors')

    @else
        <strong>You must be <a href="{{route('login')}}">logged in</a> to post a comment</strong>

    @endif
    <hr>





    @foreach($post->comment as $comment)
        <p>Auteur: {{$comment->user->name}}</p><br>
        <p>Commentaire: {{$comment->content}}</p>
        <form action="{{route('comment.destroy', $comment->id)}}" method="POST">
            {{csrf_field()}}
            <input type="hidden" name="_method" value="DELETE">
            <button>Supprimer le commentaire</button>

    @endforeach


@endsection